version: '3'

services:
  app:
    image: training:latest
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: Training
    depends_on:
      - db
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1111

  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1111
#
#version: '3'
#
#services:
#  app:
#    image: training:latest
#    ports:
#      - "8080:8080"
#    build:
#      context: .
#    container_name: Training
#    depends_on:
#      - localhost
#    environment:
#      - PORT=8080
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=1111
#
#  localhost:
#    image: postgres
#    container_name: postgres
#    environment:
#      - POSTGRES_DB=test
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=1111