version: '3'
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5433:5432