/*
 * This file is generated by jOOQ.
 */
package com.example.training.jooq.tables.records;


import com.example.training.jooq.tables.Line;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LineRecord extends UpdatableRecordImpl<LineRecord> implements Record4<Integer, LocalDate, Integer, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.line.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.line.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.line.creation_date</code>.
     */
    public void setCreationDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.line.creation_date</code>.
     */
    public LocalDate getCreationDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.line.length</code>.
     */
    public void setLength(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.line.length</code>.
     */
    public Integer getLength() {
        return (Integer) get(2);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setGeom(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getGeom() {
        return get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, LocalDate, Integer, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, LocalDate, Integer, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Line.LINE.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return Line.LINE.CREATION_DATE;
    }

    @Override
    public Field<Integer> field3() {
        return Line.LINE.LENGTH;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return Line.LINE.GEOM;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getCreationDate();
    }

    @Override
    public Integer component3() {
        return getLength();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getGeom();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getCreationDate();
    }

    @Override
    public Integer value3() {
        return getLength();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getGeom();
    }

    @Override
    public LineRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LineRecord value2(LocalDate value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public LineRecord value3(Integer value) {
        setLength(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public LineRecord value4(Object value) {
        setGeom(value);
        return this;
    }

    @Override
    public LineRecord values(Integer value1, LocalDate value2, Integer value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LineRecord
     */
    public LineRecord() {
        super(Line.LINE);
    }

    /**
     * Create a detached, initialised LineRecord
     */
    public LineRecord(Integer id, LocalDate creationDate, Integer length, Object geom) {
        super(Line.LINE);

        setId(id);
        setCreationDate(creationDate);
        setLength(length);
        setGeom(geom);
    }
}
