/*
 * This file is generated by jOOQ.
 */
package com.example.training.jooq.tables;


import com.example.training.jooq.Keys;
import com.example.training.jooq.Public;
import com.example.training.jooq.tables.records.LineRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Line extends TableImpl<LineRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.line</code>
     */
    public static final Line LINE = new Line();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LineRecord> getRecordType() {
        return LineRecord.class;
    }

    /**
     * The column <code>public.line.id</code>.
     */
    public final TableField<LineRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.line.date</code>.
     */
    public final TableField<LineRecord, LocalDateTime> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.line.length</code>.
     */
    public final TableField<LineRecord, Integer> LENGTH = createField(DSL.name("length"), SQLDataType.INTEGER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<LineRecord, Object> GEOMETRY = createField(DSL.name("geometry"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "");

    private Line(Name alias, Table<LineRecord> aliased) {
        this(alias, aliased, null);
    }

    private Line(Name alias, Table<LineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.line</code> table reference
     */
    public Line(String alias) {
        this(DSL.name(alias), LINE);
    }

    /**
     * Create an aliased <code>public.line</code> table reference
     */
    public Line(Name alias) {
        this(alias, LINE);
    }

    /**
     * Create a <code>public.line</code> table reference
     */
    public Line() {
        this(DSL.name("line"), null);
    }

    public <O extends Record> Line(Table<O> child, ForeignKey<O, LineRecord> key) {
        super(child, key, LINE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<LineRecord, Integer> getIdentity() {
        return (Identity<LineRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LineRecord> getPrimaryKey() {
        return Keys.LINE_PKEY;
    }

    @Override
    public List<UniqueKey<LineRecord>> getKeys() {
        return Arrays.<UniqueKey<LineRecord>>asList(Keys.LINE_PKEY);
    }

    @Override
    public Line as(String alias) {
        return new Line(DSL.name(alias), this);
    }

    @Override
    public Line as(Name alias) {
        return new Line(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Line rename(String name) {
        return new Line(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Line rename(Name name) {
        return new Line(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, LocalDateTime, Integer, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
