/*
 * This file is generated by jOOQ.
 */
package com.example.training.jooq;


import com.example.training.jooq.tables.Role;
import com.example.training.jooq.tables.UserEntity;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user_entity</code>.
     */
    public static final UserEntity USER_ENTITY = UserEntity.USER_ENTITY;
}
